name: VSCode + Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Lock to the version shipped with VSCode 1.36+
        node-version: ['10.10']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install latest Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - run: npm ci
      - run: npm run prettier -- --list-different
      - run: npm run compile
      - run: npm run lint
      - run: npm audit
      - name: Run headless tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test
